version: '3.8'
services:
  wineml_registry_service:
    container_name: wineml_registry_service_container
    build:
      context: ./wineml_registry/service
      dockerfile: ./docker/Dockerfile.azure
    image: wineml_registry_service_image
    networks:
      - wineml-network
    # ports:
    #   - 8081:8081
    environment:
      # AZURE EXAMPLE
      - AZURE_ACCOUNT_NAME="YOUR_ACCOUNT_NAME"
      - AZURE_CONTAINER_NAME="YOUR_CONTAINER_NAME"
      - AZURE_STORAGE_CONNECTION_STRING="YOUR_CONNECTION_STRING"

  wineml_registry_ui:
    container_name: wineml_registry_ui_container
    build:
      context: ./wineml_registry/ui
    image: wineml_registry_ui_image
    networks:
      - wineml-network
    ports:
      - 3000:3000
    depends_on:
      - wineml_registry_service
    environment:
      - REACT_APP_WINEML_SERVICE_URL=http://wineml_registry_service:8081

networks:
  wineml-network:
