version: '3.8'
services:
  wineml_registry_service:
    container_name: wineml_registry_service_container
    build:
      context: ./wineml_registry/service
      dockerfile: ./docker/Dockerfile.azure
    image: wineml_registry_service_image
    networks:
      - wineml-network
    # ports:
    #   - 8081:8081
    environment:
      # AWS S3 EXAMPLE
      - AWS_S3_BUCKET_NAME=${AWS_S3_BUCKET_NAME}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      # AZURE BLOB EXAMPLE
      - AZURE_ACCOUNT_NAME=${AZURE_ACCOUNT_NAME}
      - AZURE_CONTAINER_NAME=${AZURE_CONTAINER_NAME}
      - AZURE_STORAGE_CONNECTION_STRING=${AZURE_STORAGE_CONNECTION_STRING}

  wineml_registry_ui:
    container_name: wineml_registry_ui_container
    build:
      context: ./wineml_registry/ui
    image: wineml_registry_ui_image
    networks:
      - wineml-network
    ports:
      - 3000:3000
    depends_on:
      - wineml_registry_service
    environment:
      - REACT_APP_WINEML_SERVICE_URL=http://wineml_registry_service:8081

networks:
  wineml-network:
